// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleSchoolManagermentV1.Datas;

#nullable disable

namespace SampleSchoolManagermentV1.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20230205141845_UpdateInforTimeTable")]
    partial class UpdateInforTimeTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SampleSchoolManagermentV1.Entities.InforClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ClassName")
                        .HasColumnOrder(1);

                    b.Property<int>("Grade")
                        .HasMaxLength(12)
                        .HasColumnType("integer")
                        .HasColumnName("Grade");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TeacherName");

                    b.HasKey("Id");

                    b.ToTable("InforClass", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassName = "1A",
                            Grade = 1,
                            TeacherName = "Nguyen Thi Hanh"
                        },
                        new
                        {
                            Id = 2,
                            ClassName = "1B",
                            Grade = 1,
                            TeacherName = "Nguyen Thi Hoa"
                        },
                        new
                        {
                            Id = 3,
                            ClassName = "2A",
                            Grade = 2,
                            TeacherName = "Nguyen Van Thanh"
                        },
                        new
                        {
                            Id = 4,
                            ClassName = "2B",
                            Grade = 2,
                            TeacherName = "Chu Thi Hanh"
                        },
                        new
                        {
                            Id = 5,
                            ClassName = "3A",
                            Grade = 3,
                            TeacherName = "Nguyen Thi Thuy"
                        },
                        new
                        {
                            Id = 6,
                            ClassName = "3B",
                            Grade = 3,
                            TeacherName = "Chu Thi Thuy"
                        },
                        new
                        {
                            Id = 7,
                            ClassName = "4A",
                            Grade = 4,
                            TeacherName = "Hoang Thi Tham"
                        },
                        new
                        {
                            Id = 8,
                            ClassName = "4B",
                            Grade = 4,
                            TeacherName = "Vuong Thi Minh Hanh"
                        },
                        new
                        {
                            Id = 9,
                            ClassName = "5A",
                            Grade = 5,
                            TeacherName = "Hoang Thi Hoa"
                        },
                        new
                        {
                            Id = 10,
                            ClassName = "5B",
                            Grade = 5,
                            TeacherName = "Pham Thi Chuc"
                        },
                        new
                        {
                            Id = 11,
                            ClassName = "1C",
                            Grade = 1,
                            TeacherName = "Hoang Thi Tham"
                        },
                        new
                        {
                            Id = 12,
                            ClassName = "1D",
                            Grade = 1,
                            TeacherName = "Vuong Thi Minh Hanh"
                        },
                        new
                        {
                            Id = 13,
                            ClassName = "2C",
                            Grade = 2,
                            TeacherName = "Hoang Thi Hoa"
                        },
                        new
                        {
                            Id = 14,
                            ClassName = "2D",
                            Grade = 2,
                            TeacherName = "Pham Thi Chuc"
                        });
                });

            modelBuilder.Entity("SampleSchoolManagermentV1.Entities.InforMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("Mark")
                        .HasColumnType("real");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("typeOfMark")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentMark");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mark = 4f,
                            StudentId = 1,
                            SubjectId = 1,
                            typeOfMark = "15 phut"
                        },
                        new
                        {
                            Id = 2,
                            Mark = 5f,
                            StudentId = 2,
                            SubjectId = 1,
                            typeOfMark = "15 phut"
                        },
                        new
                        {
                            Id = 3,
                            Mark = 7f,
                            StudentId = 3,
                            SubjectId = 1,
                            typeOfMark = "15 phut"
                        },
                        new
                        {
                            Id = 4,
                            Mark = 6f,
                            StudentId = 4,
                            SubjectId = 1,
                            typeOfMark = "15 phut"
                        },
                        new
                        {
                            Id = 5,
                            Mark = 8f,
                            StudentId = 5,
                            SubjectId = 1,
                            typeOfMark = "15 phut"
                        },
                        new
                        {
                            Id = 6,
                            Mark = 9f,
                            StudentId = 6,
                            SubjectId = 1,
                            typeOfMark = "15 phut"
                        },
                        new
                        {
                            Id = 7,
                            Mark = 8f,
                            StudentId = 1,
                            SubjectId = 1,
                            typeOfMark = "1 Tiet"
                        },
                        new
                        {
                            Id = 8,
                            Mark = 5f,
                            StudentId = 2,
                            SubjectId = 1,
                            typeOfMark = "1 Tiet"
                        },
                        new
                        {
                            Id = 9,
                            Mark = 7f,
                            StudentId = 3,
                            SubjectId = 1,
                            typeOfMark = "1 Tiet"
                        },
                        new
                        {
                            Id = 10,
                            Mark = 4f,
                            StudentId = 4,
                            SubjectId = 1,
                            typeOfMark = "1 Tiet"
                        },
                        new
                        {
                            Id = 11,
                            Mark = 6f,
                            StudentId = 5,
                            SubjectId = 1,
                            typeOfMark = "1 Tiet"
                        },
                        new
                        {
                            Id = 12,
                            Mark = 9f,
                            StudentId = 6,
                            SubjectId = 1,
                            typeOfMark = "1 Tiet"
                        },
                        new
                        {
                            Id = 13,
                            Mark = 8f,
                            StudentId = 1,
                            SubjectId = 1,
                            typeOfMark = "Giua ki"
                        },
                        new
                        {
                            Id = 14,
                            Mark = 4f,
                            StudentId = 2,
                            SubjectId = 1,
                            typeOfMark = "Giua ki"
                        },
                        new
                        {
                            Id = 15,
                            Mark = 6f,
                            StudentId = 3,
                            SubjectId = 1,
                            typeOfMark = "Giua ki"
                        },
                        new
                        {
                            Id = 16,
                            Mark = 4f,
                            StudentId = 4,
                            SubjectId = 1,
                            typeOfMark = "Giua ki"
                        },
                        new
                        {
                            Id = 17,
                            Mark = 5f,
                            StudentId = 5,
                            SubjectId = 1,
                            typeOfMark = "Giua ki"
                        },
                        new
                        {
                            Id = 18,
                            Mark = 7f,
                            StudentId = 6,
                            SubjectId = 1,
                            typeOfMark = "Giua ki"
                        },
                        new
                        {
                            Id = 19,
                            Mark = 7f,
                            StudentId = 1,
                            SubjectId = 1,
                            typeOfMark = "Cuoi ki"
                        },
                        new
                        {
                            Id = 20,
                            Mark = 4f,
                            StudentId = 2,
                            SubjectId = 1,
                            typeOfMark = "Cuoi ki"
                        },
                        new
                        {
                            Id = 21,
                            Mark = 5f,
                            StudentId = 3,
                            SubjectId = 1,
                            typeOfMark = "Cuoi ki"
                        },
                        new
                        {
                            Id = 22,
                            Mark = 7f,
                            StudentId = 4,
                            SubjectId = 1,
                            typeOfMark = "Cuoi ki"
                        },
                        new
                        {
                            Id = 23,
                            Mark = 8f,
                            StudentId = 5,
                            SubjectId = 1,
                            typeOfMark = "Cuoi ki"
                        },
                        new
                        {
                            Id = 24,
                            Mark = 9f,
                            StudentId = 6,
                            SubjectId = 1,
                            typeOfMark = "Cuoi ki"
                        },
                        new
                        {
                            Id = 25,
                            Mark = 9f,
                            StudentId = 1,
                            SubjectId = 2,
                            typeOfMark = "15 phut"
                        },
                        new
                        {
                            Id = 26,
                            Mark = 9f,
                            StudentId = 1,
                            SubjectId = 2,
                            typeOfMark = "1 tiet"
                        },
                        new
                        {
                            Id = 27,
                            Mark = 9f,
                            StudentId = 1,
                            SubjectId = 2,
                            typeOfMark = "Giua ki"
                        },
                        new
                        {
                            Id = 28,
                            Mark = 9f,
                            StudentId = 1,
                            SubjectId = 2,
                            typeOfMark = "Cuoi ki"
                        },
                        new
                        {
                            Id = 29,
                            Mark = 6f,
                            StudentId = 1,
                            SubjectId = 3,
                            typeOfMark = "15 phut"
                        },
                        new
                        {
                            Id = 30,
                            Mark = 5f,
                            StudentId = 1,
                            SubjectId = 3,
                            typeOfMark = "1 tiet"
                        },
                        new
                        {
                            Id = 31,
                            Mark = 6f,
                            StudentId = 1,
                            SubjectId = 3,
                            typeOfMark = "Giua ki"
                        },
                        new
                        {
                            Id = 32,
                            Mark = 7f,
                            StudentId = 1,
                            SubjectId = 3,
                            typeOfMark = "Cuoi ki"
                        });
                });

            modelBuilder.Entity("SampleSchoolManagermentV1.Entities.InforStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Address");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("FatherName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FatherName");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit")
                        .HasColumnName("Gender");

                    b.Property<string>("MotherName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MotherName");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("StudentName");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Student", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ha Noi",
                            ClassId = 1,
                            DateOfBirth = new DateTime(2015, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "",
                            Gender = true,
                            MotherName = "",
                            StudentName = "Nguyen Khanh Toan"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ha Noi",
                            ClassId = 1,
                            DateOfBirth = new DateTime(2015, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "",
                            Gender = false,
                            MotherName = "",
                            StudentName = "Nguyen Ngoc Long"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ha Noi",
                            ClassId = 2,
                            DateOfBirth = new DateTime(2015, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "",
                            Gender = true,
                            MotherName = "",
                            StudentName = "Chu Khanh Toan"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Ha Noi",
                            ClassId = 2,
                            DateOfBirth = new DateTime(2015, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "",
                            Gender = true,
                            MotherName = "",
                            StudentName = "Hoang Van Long"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Ha Noi",
                            ClassId = 3,
                            DateOfBirth = new DateTime(2014, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "",
                            Gender = false,
                            MotherName = "",
                            StudentName = "Pham Thanh Xuan"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Ha Noi",
                            ClassId = 3,
                            DateOfBirth = new DateTime(2014, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "",
                            Gender = true,
                            MotherName = "",
                            StudentName = "Vu Duc Khanh"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Ha Noi",
                            ClassId = 4,
                            DateOfBirth = new DateTime(2014, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "",
                            Gender = false,
                            MotherName = "",
                            StudentName = "Chuong Thi Khanh Toan"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Ha Noi",
                            ClassId = 4,
                            DateOfBirth = new DateTime(2014, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "",
                            Gender = true,
                            MotherName = "",
                            StudentName = "Nguyen Thanh Long"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Ha Noi",
                            ClassId = 5,
                            DateOfBirth = new DateTime(2013, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "",
                            Gender = false,
                            MotherName = "",
                            StudentName = "Do Thi Huong"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Ha Noi",
                            ClassId = 5,
                            DateOfBirth = new DateTime(2013, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "",
                            Gender = true,
                            MotherName = "",
                            StudentName = "Truong Dang Hieu"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Ha Noi",
                            ClassId = 6,
                            DateOfBirth = new DateTime(2013, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "",
                            Gender = true,
                            MotherName = "",
                            StudentName = "Truong Quoc Sinh"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Ha Noi",
                            ClassId = 6,
                            DateOfBirth = new DateTime(2013, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "",
                            Gender = false,
                            MotherName = "",
                            StudentName = "Nguyen Thu Huong"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Ha Noi",
                            ClassId = 6,
                            DateOfBirth = new DateTime(2013, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "",
                            Gender = false,
                            MotherName = "",
                            StudentName = "Do Thi Mai"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Ha Noi",
                            ClassId = 1,
                            DateOfBirth = new DateTime(2015, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FatherName = "",
                            Gender = true,
                            MotherName = "",
                            StudentName = "Nguyen Khanh Mai"
                        });
                });

            modelBuilder.Entity("SampleSchoolManagermentV1.Entities.InforSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("SlotInWeek")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grade = 1,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Toan"
                        },
                        new
                        {
                            Id = 2,
                            Grade = 1,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Toan"
                        },
                        new
                        {
                            Id = 3,
                            Grade = 1,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Van"
                        },
                        new
                        {
                            Id = 4,
                            Grade = 1,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Van"
                        },
                        new
                        {
                            Id = 5,
                            Grade = 1,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Anh"
                        },
                        new
                        {
                            Id = 6,
                            Grade = 1,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Anh"
                        },
                        new
                        {
                            Id = 7,
                            Grade = 1,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Hoa"
                        },
                        new
                        {
                            Id = 8,
                            Grade = 1,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Hoa"
                        },
                        new
                        {
                            Id = 9,
                            Grade = 1,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Li"
                        },
                        new
                        {
                            Id = 10,
                            Grade = 1,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Li"
                        },
                        new
                        {
                            Id = 11,
                            Grade = 1,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Sinh"
                        },
                        new
                        {
                            Id = 12,
                            Grade = 1,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Sinh"
                        },
                        new
                        {
                            Id = 13,
                            Grade = 1,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "GDCD"
                        },
                        new
                        {
                            Id = 14,
                            Grade = 1,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "GDCD"
                        },
                        new
                        {
                            Id = 15,
                            Grade = 2,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Toan"
                        },
                        new
                        {
                            Id = 16,
                            Grade = 2,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Toan"
                        },
                        new
                        {
                            Id = 17,
                            Grade = 2,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Van"
                        },
                        new
                        {
                            Id = 18,
                            Grade = 2,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Van"
                        },
                        new
                        {
                            Id = 19,
                            Grade = 2,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Anh"
                        },
                        new
                        {
                            Id = 20,
                            Grade = 2,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Anh"
                        },
                        new
                        {
                            Id = 21,
                            Grade = 2,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Hoa"
                        },
                        new
                        {
                            Id = 22,
                            Grade = 2,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Hoa"
                        },
                        new
                        {
                            Id = 23,
                            Grade = 2,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Li"
                        },
                        new
                        {
                            Id = 24,
                            Grade = 2,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Li"
                        },
                        new
                        {
                            Id = 25,
                            Grade = 2,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Sinh"
                        },
                        new
                        {
                            Id = 26,
                            Grade = 2,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Sinh"
                        },
                        new
                        {
                            Id = 27,
                            Grade = 2,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "GDCD"
                        },
                        new
                        {
                            Id = 28,
                            Grade = 2,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "GDCD"
                        },
                        new
                        {
                            Id = 29,
                            Grade = 3,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Toan"
                        },
                        new
                        {
                            Id = 30,
                            Grade = 3,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Toan"
                        },
                        new
                        {
                            Id = 31,
                            Grade = 3,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Van"
                        },
                        new
                        {
                            Id = 32,
                            Grade = 3,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Van"
                        },
                        new
                        {
                            Id = 33,
                            Grade = 3,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Anh"
                        },
                        new
                        {
                            Id = 34,
                            Grade = 3,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Anh"
                        },
                        new
                        {
                            Id = 35,
                            Grade = 3,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Hoa"
                        },
                        new
                        {
                            Id = 36,
                            Grade = 3,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Hoa"
                        },
                        new
                        {
                            Id = 37,
                            Grade = 3,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Li"
                        },
                        new
                        {
                            Id = 38,
                            Grade = 3,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Li"
                        },
                        new
                        {
                            Id = 39,
                            Grade = 3,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Sinh"
                        },
                        new
                        {
                            Id = 40,
                            Grade = 3,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Sinh"
                        },
                        new
                        {
                            Id = 41,
                            Grade = 3,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "GDCD"
                        },
                        new
                        {
                            Id = 42,
                            Grade = 3,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "GDCD"
                        },
                        new
                        {
                            Id = 43,
                            Grade = 4,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Toan"
                        },
                        new
                        {
                            Id = 44,
                            Grade = 4,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Toan"
                        },
                        new
                        {
                            Id = 45,
                            Grade = 4,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Van"
                        },
                        new
                        {
                            Id = 46,
                            Grade = 4,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Van"
                        },
                        new
                        {
                            Id = 47,
                            Grade = 4,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Anh"
                        },
                        new
                        {
                            Id = 48,
                            Grade = 4,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Anh"
                        },
                        new
                        {
                            Id = 49,
                            Grade = 4,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Hoa"
                        },
                        new
                        {
                            Id = 50,
                            Grade = 4,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Hoa"
                        },
                        new
                        {
                            Id = 51,
                            Grade = 4,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Li"
                        },
                        new
                        {
                            Id = 52,
                            Grade = 4,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Li"
                        },
                        new
                        {
                            Id = 53,
                            Grade = 4,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Sinh"
                        },
                        new
                        {
                            Id = 54,
                            Grade = 4,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Sinh"
                        },
                        new
                        {
                            Id = 55,
                            Grade = 4,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "GDCD"
                        },
                        new
                        {
                            Id = 56,
                            Grade = 4,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "GDCD"
                        },
                        new
                        {
                            Id = 57,
                            Grade = 5,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Toan"
                        },
                        new
                        {
                            Id = 58,
                            Grade = 5,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Toan"
                        },
                        new
                        {
                            Id = 59,
                            Grade = 5,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Van"
                        },
                        new
                        {
                            Id = 60,
                            Grade = 5,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Van"
                        },
                        new
                        {
                            Id = 61,
                            Grade = 5,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Anh"
                        },
                        new
                        {
                            Id = 62,
                            Grade = 5,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Anh"
                        },
                        new
                        {
                            Id = 63,
                            Grade = 5,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Hoa"
                        },
                        new
                        {
                            Id = 64,
                            Grade = 5,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Hoa"
                        },
                        new
                        {
                            Id = 65,
                            Grade = 5,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Li"
                        },
                        new
                        {
                            Id = 66,
                            Grade = 5,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Li"
                        },
                        new
                        {
                            Id = 67,
                            Grade = 5,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "Sinh"
                        },
                        new
                        {
                            Id = 68,
                            Grade = 5,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "Sinh"
                        },
                        new
                        {
                            Id = 69,
                            Grade = 5,
                            Semester = 1,
                            SlotInWeek = 5,
                            SubjectName = "GDCD"
                        },
                        new
                        {
                            Id = 70,
                            Grade = 5,
                            Semester = 2,
                            SlotInWeek = 5,
                            SubjectName = "GDCD"
                        });
                });

            modelBuilder.Entity("SampleSchoolManagermentV1.Entities.InforTimeTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Classid")
                        .HasColumnType("int");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("slot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Classid");

                    b.HasIndex("SubjectId");

                    b.ToTable("TimeTable");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SampleSchoolManagermentV1.Entities.InforMark", b =>
                {
                    b.HasOne("SampleSchoolManagermentV1.Entities.InforStudent", "InformationStudent")
                        .WithMany("InformationMarks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SampleSchoolManagermentV1.Entities.InforSubject", "InformationSubject")
                        .WithMany("InformationMarks")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InformationStudent");

                    b.Navigation("InformationSubject");
                });

            modelBuilder.Entity("SampleSchoolManagermentV1.Entities.InforStudent", b =>
                {
                    b.HasOne("SampleSchoolManagermentV1.Entities.InforClass", "InformationClass")
                        .WithMany("InformationStudents")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InformationClass");
                });

            modelBuilder.Entity("SampleSchoolManagermentV1.Entities.InforTimeTable", b =>
                {
                    b.HasOne("SampleSchoolManagermentV1.Entities.InforClass", "InformationClass")
                        .WithMany()
                        .HasForeignKey("Classid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SampleSchoolManagermentV1.Entities.InforSubject", "InformationSubject")
                        .WithMany("InforTimeTables")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InformationClass");

                    b.Navigation("InformationSubject");
                });

            modelBuilder.Entity("SampleSchoolManagermentV1.Entities.InforClass", b =>
                {
                    b.Navigation("InformationStudents");
                });

            modelBuilder.Entity("SampleSchoolManagermentV1.Entities.InforStudent", b =>
                {
                    b.Navigation("InformationMarks");
                });

            modelBuilder.Entity("SampleSchoolManagermentV1.Entities.InforSubject", b =>
                {
                    b.Navigation("InforTimeTables");

                    b.Navigation("InformationMarks");
                });
#pragma warning restore 612, 618
        }
    }
}
